{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm-operator.name" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "slurm-operator.operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slurm-operator.operator.labels" . | nindent 8 }}
    spec:
      hostname: {{ include "slurm-operator.name" . }}
      priorityClassName: {{ default "" .Values.priorityClassName }}
      serviceAccountName: {{ include "slurm-operator.operator.serviceAccountName" . }}
      {{- include "slurm-operator.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: slurm-operator
          image: {{ include "slurm-operator.operator.imageRef" . }}
          imagePullPolicy: {{ include "slurm-operator.imagePullPolicy" . }}
          args:
            {{- with .Values.operator.clusterWorkers }}
            - --cluster-workers
            - {{ . | quote }}
            {{- end }}{{- /* with .Values.operator.clusterWorkers */}}
            {{- with .Values.operator.nodesetWorkers }}
            - --nodeset-workers
            - {{ . | quote }}
            {{- end }}{{- /* with .Values.operator.nodesetWorkers */}}
            {{- with .Values.operator.logLevel }}
            - --zap-log-level
            - {{ . | quote }}
            {{- end }}{{- /* with .Values.operator.logLevel */}}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.operator.affinity */}}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.operator.tolerations */}}
{{- end }}{{- /* if .Values.operator.enabled */}}
