apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.openshift.io/runtime: mariadb
    template: mariadb-persistent-template
  name: {{ .Values.database_service_name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume_capacity }}
