apiVersion: v1
kind: Service
metadata:
  name: {{ include "glauth.fullname" . }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: glauth-tls
spec:
  selector:
    {{- include "glauth.selectorLabels" . | nindent 4 }}
  ports:
  - name: ldap
    port: 389
    targetPort: 3893
  - name: ldaps
    port: 636
    targetPort: 3894
  - name: additional
    port: 5555
    targetPort: 5555
  type: ClusterIP
