---
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta13
kind: Config
deploy:
  helm:
    releases:
      - name: slurm
        chartPath: ./
        valuesFiles:
          - ./values-dev.yaml
        namespace: slurm
        createNamespace: true
# https://skaffold.dev/docs/port-forwarding/
portForward:
  - resourceType: service
    resourceName: slurm-restapi
    namespace: slurm
    port: 6820
