persistence:
  enabled: false
  size: 10Gi
  storageClass: ""

slurm:
  controller:
    persistence:
      storageClass: null

    imagePullPolicy: IfNotPresent
    image:
      repository: quay.io/slinky-on-openshift/slurmctld
      tag: ohpc


  mariadb:
    enabled: false
    # primary:
    #   persistence:
    #     storageClass: null
    #   containerSecurityContext:
    #     seLinuxOptions: null

  authcred:
    image:
      repository: quay.io/slinky-on-openshift/sackd
      tag: ohpc

  login:
    enabled: true

    imagePullPolicy: Always
    image:
      repository: quay.io/slinky-on-openshift/login
      tag: ohpc

    service:
      type: ClusterIP

    sssdConf:
      domains:
        DEFAULT:
          ldap_tls_reqcert: never
          ldap_uri: ldaps://slurm-glauth.slurm.svc.cluster.local
          ldap_search_base: dc=example,dc=com
          ldap_user_search_base: dc=example,dc=com
          ldap_group_search_base: dc=example,dc=com

          ldap_default_bind_dn: cn=serviceuser,dc=example,dc=com
          ldap_default_authtok: mysecret

          ldap_access_filter: (memberOf=ou=users,ou=groups,dc=example,dc=com)

    securityContext:
      runAsUser: 0
      capabilities:
        add:
          - SYS_CHROOT

  compute:
    image:
      repository: quay.io/slinky-on-openshift/slurmd
      tag: ohpc

    nodesets:
      - name: debug
        enabled: true
        replicas: 2
        imagePullPolicy: IfNotPresent
        image:
          repository: ""
          tag: ""
        nodeSelector:
          kubernetes.io/os: linux
        affinity: {}
        tolerations: []
        resources:
          requests:
            cpu: 4
            memory: 8Gi
          limits:
            cpu: 4
            memory: 8Gi
        useResourceLimits: true
        volumeClaimTemplates: []
        extraVolumeMounts: []
        extraVolumes: []
        partition:
          enabled: true
          config:
            State: UP
            MaxTime: UNLIMITED
        nodeConfig: {}
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 20%

  accounting:
    image:
      repository: quay.io/slinky-on-openshift/slurmdbd
      tag: ohpc

    external:
      enabled: true
      host: slurm-mariadb
      password: slurm

  restapi:
    image:
      repository: quay.io/slinky-on-openshift/slurmrestd
      tag: ohpc

mariadb:
  database_service_name: slurm-mariadb
  mariadb_version: 10.3-el8
  memory_limit: 512Mi
  mysql_database: slurm_acct_db
  mysql_password: slurm
  mysql_root_password: testroot
  mysql_user: slurm
  namespace: slurm
  volume_capacity: 8Gi

# MachineSet Configuration
machineset:
  enabled: false
  # Name of the existing MachineSet to base the new one on
  sourceName: ""
  # Namespace where the MachineSet exists and will be created
  namespace: "openshift-machine-api"
  # What to replace "worker" with in names and labels
  workerReplacement: "metal-worker"
  # Number of replicas (typically 0 for metal workers initially)
  replicas: 0
  # Instance type for the new MachineSet
  instanceType: "c5.metal"
  # Additional taints to add to the metal worker nodes
  additionalTaints:
    - key: "metal-worker"
      value: "true"
      effect: "PreferNoSchedule"
