apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ODF
  - github.com/redhat-cop/gitops-catalog/openshift-data-foundation-operator/instance/overlays/aws?ref=main
  # NFD
  - https://github.com/redhat-cop/gitops-catalog/nfd/instance/overlays/only-nvidia?ref=main
  # GPU
  - https://github.com/redhat-cop/gitops-catalog/gpu-operator-certified/instance/overlays/aws
