apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: openshift-machine-api

configMapGenerator:
  - name: job-aws-machineset
    namespace: openshift-machine-api
    files:
      - job.sh
