resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: glauth
    includeSelectors: true
    includeTemplates: true
