apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: slurm

priority: 10
users: []
groups:
- system:serviceaccounts:slurm

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- NET_RAW
- BPF
- NET_ADMIN
- SYS_ADMIN
- SYS_NICE
- SYS_CHROOT # needed for login nodes (sshd)
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny

seccompProfiles:
- runtime/default

volumes:
- configMap
- csi
- downwardAPI
- emptyDir
- ephemeral
- persistentVolumeClaim
- projected
- secret
