---
# Source: mariadb-persistent/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.openshift.io/runtime: mariadb
    template: mariadb-persistent-template
  name: slurm-mariadb
stringData:
  database-name: slurm_acct_db
  database-password: slurm
  database-root-password: testur
  database-user: slurm
---
# Source: mariadb-persistent/templates/persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.openshift.io/runtime: mariadb
    template: mariadb-persistent-template
  name: slurm-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
# Source: mariadb-persistent/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.openshift.io/runtime: mariadb
    template: mariadb-persistent-template
  name: slurm-mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    name: slurm-mariadb
---
# Source: mariadb-persistent/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "mariadb:10.3-el8"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
  labels:
    app.openshift.io/runtime: mariadb
    template: mariadb-persistent-template
  name: slurm-mariadb

spec:
  replicas: 1
  selector:
    matchLabels:
      name: slurm-mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: slurm-mariadb
    spec:
      serviceAccountName: db
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: slurm-mariadb
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: slurm-mariadb
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: slurm-mariadb
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: slurm-mariadb
        image: "mariadb:10.3-el8"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
          initialDelaySeconds: 30
          timeoutSeconds: 1
        name: mariadb
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: slurm-mariadb-data
      volumes:
      - name: slurm-mariadb-data
        persistentVolumeClaim:
          claimName: slurm-mariadb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db
