apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slurm-operator-token-manager
rules:
  - apiGroups:
      - slinky.slurm.net
    resources:
      - tokens
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - slinky.slurm.net
    resources:
      - tokens/finalizers
    verbs:
      - update
  - apiGroups:
      - slinky.slurm.net
    resources:
      - tokens/status
    verbs:
      - get
      - patch
      - update
