{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.login.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm.login.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm.login.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.login.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "slurm.login.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: login
      labels:
        {{- include "slurm.login.labels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.login.priorityClassName | default .Values.priorityClassName }}
      automountServiceAccountToken: false
      enableServiceLinks: false
      dnsConfig:
        {{- include "slurm.dnsConfig" . | nindent 8 }}
      initContainers:
        - name: init
          image: {{ include "slurm.authcred.imageRef" . }}
          imagePullPolicy: {{ .Values.authcred.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          {{- with .Values.authcred.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with .Values.authcred.resources */}}
          env:
            - name: SLURM_USER
              value: {{ include "slurm.user" . }}
          command:
            - tini
            - -g
            - --
            - bash
            - -c
            - |
              {{- range .Files.Lines "scripts/init.sh" }}
              {{ . }}
              {{- end }}{{- /* range .Files.Lines "scripts/init.sh" */}}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" . | nindent 12 }}
      containers:
        - name: login
          image: {{ include "slurm.login.imageRef" . }}
          imagePullPolicy: {{ .Values.login.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          {{- with .Values.login.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SACKD_OPTIONS
              value: --conf-server={{- printf "%s:%s" (include "slurm.controller.name" .) (include "slurm.controller.port" .) }}
          ports:
            - name: ssh
              containerPort: 22
          {{- with .Values.login.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with .Values.login.resources */}}
          readinessProbe:
            exec:
              command:
                - test
                - -S
                - /run/slurm/sack.socket
          volumeMounts:
            {{- include "slurm.volumeMounts" . | nindent 12 }}
            - name: authsocket
              mountPath: /run/slurm
            - name: ssh-config
              mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
              readOnly: true
            - name: ssh-config
              mountPath: /root/.ssh/authorized_keys
              subPath: authorized_keys
              readOnly: true
            - name: sssd-config
              mountPath: /etc/sssd/sssd.conf
              subPath: sssd.conf
              readOnly: true
            - name: ssh-host-keys
              mountPath: /etc/ssh/ssh_host_ecdsa_key
              subPath: ssh_host_ecdsa_key
              readOnly: true
            - name: ssh-host-keys
              mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: ssh_host_ed25519_key
              readOnly: true
            - name: ssh-host-keys
              mountPath: /etc/ssh/ssh_host_rsa_key
              subPath: ssh_host_rsa_key
              readOnly: true
            {{- with .Values.login.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}{{- /* range $vol := $.Values.login.extraVolumeMounts */}}
      {{- with .Values.accounting.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.accounting.nodeSelector */}}
      {{- with .Values.login.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.login.affinity */}}
      {{- with .Values.login.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.login.tolerations */}}
      volumes:
        {{- include "slurm.volumes" . | nindent 8 }}
        - name: ssh-config
          configMap:
            name: {{ include "slurm.login.name" . }}-config
            items:
              - key: authorized_keys
                path: authorized_keys
                mode: 0600
              - key: sshd_config
                path: sshd_config
                mode: 0600
        - name: sssd-config
          secret:
            secretName: {{ include "slurm.login.name" . }}-config
            defaultMode: 0600
        - name: ssh-host-keys
          secret:
            secretName: {{ include "slurm.login.name" . }}-ssh-host-keys
            defaultMode: 0600
        - name: slurm-config
          projected:
            defaultMode: 0600
            sources:
              - secret:
                  name: {{ include "slurm.auth.secretName" . }}
        - name: authsocket
          emptyDir: {}
        {{- with .Values.login.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}{{- /* with .Values.login.volumes */}}
{{- end }}{{- /* if .Values.login.enabled */}}
