resources:
  - ../base

helmCharts:
  - name: slurm
    repo: oci://ghcr.io/slinkyproject/charts/
    version: 0.3.0
    releaseName: slurm
    namespace: slurm
    skipTests: true
    valuesFile: ../base/values.yaml

patches:
  - target:
      kind: NodeSet
      name: slurm-compute-debug
    patch: |-
      - op: replace
        path: /spec/template/spec/priorityClassName
        value: ""
