apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # web terminal
  - https://github.com/redhat-cop/gitops-catalog/web-terminal/operator/overlays/fast?ref=main
  # ODF 4.18
  - github.com/redhat-cop/gitops-catalog/openshift-data-foundation-operator/operator/overlays/stable-4.18?ref=main
  - github.com/redhat-cop/gitops-catalog/openshift-data-foundation-operator/config-helpers/node-labeler/overlays/default?ref=main
  # NFD
  - https://github.com/redhat-cop/gitops-catalog/nfd/operator/overlays/stable?ref=main
  # GPU
  - https://github.com/redhat-cop/gitops-catalog/gpu-operator-certified/operator/overlays/stable?ref=main

  - disable-lightspeed.yaml

# because stable-4.19 doesn't exist for ODF yet
# # - github.com/redhat-cop/gitops-catalog/openshift-data-foundation-operator/operator/base?ref=main
#
# patches:
#   - target:
#       group: operators.coreos.com
#       kind: Subscription
#       name: odf-operator
#       namespace: openshift-storage
#       version: v1alpha1
#     patch: |-
#       - op: replace
#         path: /spec/channel
#         value: stable-4.19
