apiVersion: apps/v1
kind: Deployment
metadata:
  name: homearea-tools
spec:
  selector:
    matchLabels:
      app: homearea-tools
  replicas: 1
  template:
    metadata:
      labels:
        app: homearea-tools
    spec:
      containers:
        - name: homearea
          image: docker.io/busybox:latest
          securityContext:
            runAsUser: 0
          command:
            - /bin/sh
            - -c
            - "sleep infinity"
          volumeMounts:
            - name: homearea
              mountPath: /home
      volumes:
        - name: homearea
          persistentVolumeClaim:
            claimName: user-homearea
