apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-homearea
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: simple-nfs
  volumeMode: Filesystem
