controller:
  persistence:
    storageClass: null

mariadb:
  enabled: false
  # primary:
  #   persistence:
  #     storageClass: null
  #   containerSecurityContext:
  #     seLinuxOptions: null

authcred:
  image:
    repository: quay.io/slinky-on-openshift/sackd
    tag: '25.05'

login:
  enabled: true

  imagePullPolicy: Always
  image:
    repository: quay.io/slinky-on-openshift/login-extra
    tag: '25.05'

  service:
    type: ClusterIP

  sssdConf:
    domains:
      DEFAULT:
        ldap_tls_reqcert: never
        ldap_uri: ldaps://glauth.slurm.svc.cluster.local
        ldap_search_base: dc=example,dc=com
        ldap_user_search_base: dc=example,dc=com
        ldap_group_search_base: dc=example,dc=com

        ldap_default_bind_dn: cn=serviceuser,dc=example,dc=com
        ldap_default_authtok: mysecret

        ldap_access_filter: (memberOf=ou=users,ou=groups,dc=example,dc=com)

  securityContext:
    runAsUser: 0
    capabilities:
      add:
        - SYS_CHROOT

compute:
  image:
    repository: quay.io/slinky-on-openshift/slurmd-extra
    tag: '25.05'

  # Must have key values out of the array to override instead
  # of append, behavior is non-deterministic
  nodesets:
    - name: debug
      enabled: true
      replicas: 2
      imagePullPolicy: IfNotPresent
      image:
        repository: ""
        tag: ""
      priorityClassName: slurm
      nodeSelector:
        kubernetes.io/os: linux
      affinity: {}
      tolerations: []
      resources: {}
      useResourceLimits: true
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 20%
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain
      volumeClaimTemplates: []
      extraVolumeMounts: []
      extraVolumes: []
      partition:
        enabled: true
        config:
          State: UP
          MaxTime: UNLIMITED
      nodeConfig: {}

accounting:
  image:
    repository: quay.io/slinky-on-openshift/slurmdbd
    tag: '25.05'

  external:
    enabled: true
    host: slurm-mariadb
    password: slurm

restapi:
  image:
    repository: quay.io/slinky-on-openshift/slurmrestd
    tag: '25.05'
