slurm:
  compute:
    nodesets:
      - name: gpu
        enabled: true
        replicas: 0
        image:
          repository: quay.io/slinky-on-openshift/slurmd
          tag: '25.05-cuda'
        resources:
          requests:
            cpu: 14
            memory: 56Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 14
            memory: 56Gi
            nvidia.com/gpu: 1
        useResourceLimits: true
        partition:
          enabled: true
          config:
            State: UP
            MaxTime: UNLIMITED
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 20%

machineset:
  enabled: true
  # sourceName: "cluster-slurm-5fs8t-worker-us-east-2c"
  workerReplacement: "gpu-worker"
  replicas: 0
  instanceType: "g6.4xlarge"
  additionalTaints:
    - key: "gpu"
      value: "true"
      effect: "PreferNoSchedule"
