name: Build Slurm images

env:
  REPO: quay.io/slinky-on-openshift
  SLURM_VERSION: 25.05
  PARENT_IMAGE: registry.access.redhat.com/ubi9/ubi:latest

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  build-slurm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build parent
      run: |
        docker build --build-arg PARENT_IMAGE={{ env.PARENT_IMAGE }} \
          --tag ${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          images/parent

    - name: Build parent-cuda
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/parent:${{ env.SLURM_VERSION }}-cuda \
          images/parent-cuda

    - name: Build base
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/base:${{ env.SLURM_VERSION }} \
          --target=base \
          upstream/containers/schedmd/slurm/${{ env.SLURM_VERSION }}/rockylinux9
        docker push ${{ env.REPO }}/base:${{ env.SLURM_VERSION }}

    - name: Build slurmd
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/slurmd:${{ env.SLURM_VERSION }} \
          --target=slurmd \
          upstream/containers/schedmd/slurm/${{ env.SLURM_VERSION }}/rockylinux9
        docker push ${{ env.REPO }}/slurmd:${{ env.SLURM_VERSION }}

    - name: Build slurmd-cuda
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }}-cuda \
          --tag ${{ env.REPO }}/slurmd:${{ env.SLURM_VERSION }}-cuda \
          --target=slurmd \
          upstream/containers/schedmd/slurm/${{ env.SLURM_VERSION }}/rockylinux9
        docker push ${{ env.REPO }}/slurmd:${{ env.SLURM_VERSION }}-cuda

    - name: Build slurmctld
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/slurmctld:${{ env.SLURM_VERSION }} \
          --target=slurmctld \
          upstream/containers/schedmd/slurm/${{ env.SLURM_VERSION }}/rockylinux9
        docker push ${{ env.REPO }}/slurmctld:${{ env.SLURM_VERSION }}

    - name: Build slurmrestd
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/slurmrestd:${{ env.SLURM_VERSION }} \
          --target=slurmrestd \
          upstream/containers/schedmd/slurm/${{ env.SLURM_VERSION }}/rockylinux9
        docker push ${{ env.REPO }}/slurmrestd:${{ env.SLURM_VERSION }}

    - name: Build slurmdbd
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/slurmdbd:${{ env.SLURM_VERSION }} \
          --target=slurmdbd \
          upstream/containers/schedmd/slurm/${{ env.SLURM_VERSION }}/rockylinux9
        docker push ${{ env.REPO }}/slurmdbd:${{ env.SLURM_VERSION }}

    - name: Build sackd
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/sackd:${{ env.SLURM_VERSION }} \
          --target=sackd \
          upstream/containers/schedmd/slurm/${{ env.SLURM_VERSION }}/rockylinux9
        docker push ${{ env.REPO }}/sackd:${{ env.SLURM_VERSION }}

    - name: Build login
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/parent:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/login:${{ env.SLURM_VERSION }} \
          --target=login \
          upstream/containers/schedmd/slurm/${{ env.SLURM_VERSION }}/rockylinux9
        docker push ${{ env.REPO }}/login:${{ env.SLURM_VERSION }}

    - name: Build login-extra
      run: |
        docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/login:${{ env.SLURM_VERSION }} \
          --tag ${{ env.REPO }}/login-extra:${{ env.SLURM_VERSION }} \
          images/login
        docker push ${{ env.REPO }}/login-extra:${{ env.SLURM_VERSION }}

    # - name: Build slurm workbench
    #   run: |
    #     docker build --build-arg PARENT_IMAGE=${{ env.REPO }}/base:${{ env.SLURM_VERSION }} \
    #       --tag ${{ env.REPO }}/workbench:${{ env.SLURM_VERSION }} \
    #       images/workbench
    #     docker push ${{ env.REPO }}/workbench:${{ env.SLURM_VERSION }}
