name: Build OpenHPC-based Slurm images

env:
  REPO: quay.io/slinky-on-openshift
  PARENT_IMAGE: quay.io/centos/centos:stream9

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build base image
        run: |
          docker build --tag ${{ env.REPO }}/base:ohpc --target=base \
            --build-arg PARENT_IMAGE=${{ env.PARENT_IMAGE }} \
            images/ohpc
          docker push ${{ env.REPO }}/base:ohpc

  build-components:
    needs: build-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [slurmd, slurmctld, slurmrestd, slurmdbd, sackd, login]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Pull base image
        run: docker pull ${{ env.REPO }}/base:ohpc

      - name: Build ${{ matrix.component }} image
        run: |
          docker build --tag ${{ env.REPO }}/${{ matrix.component }}:ohpc --target=${{ matrix.component }} \
            --build-arg BASE_IMAGE=${{ env.REPO }}/base:ohpc \
            images/ohpc
          docker push ${{ env.REPO }}/${{ matrix.component }}:ohpc
