name: Build OpenHPC-based Slurm images

env:
  REPO: quay.io/slinky-on-openshift
  PARENT_IMAGE: quay.io/centos/centos:stream9

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  build-base:
    runs-on: ubuntu-latest
    outputs:
      base_image: ${{ steps.build-base.outputs.image }}
    steps:
    - uses: actions/checkout@v3

    - name: Login to quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and export base image
      id: build-base
      uses: docker/build-push-action@v4
      with:
        context: images/ohpc
        tags: ${{ env.REPO }}/base:ohpc
        outputs: type=docker,dest=/tmp/base.tar
        target: base
        build-args: |
          PARENT_IMAGE=${{ env.PARENT_IMAGE }}
        push: false

    - name: Push base image
      run: |
        docker load < /tmp/base.tar
        docker push ${{ env.REPO }}/base:ohpc
        echo "image=${{ env.REPO }}/base:ohpc" >> $GITHUB_OUTPUT

    - name: Upload base image
      uses: actions/upload-artifact@v3
      with:
        name: base-image
        path: /tmp/base.tar
        retention-days: 1

  build-images:
    needs: build-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [slurmd, slurmctld, slurmrestd, slurmdbd, sackd, login]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Login to quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Download base image
      uses: actions/download-artifact@v3
      with:
        name: base-image
        path: /tmp

    - name: Load base image
      run: |
        docker load < /tmp/base.tar

    - name: Build and push ${{ matrix.target }} image
      uses: docker/build-push-action@v4
      with:
        context: images/ohpc
        tags: ${{ env.REPO }}/${{ matrix.target }}:ohpc
        target: ${{ matrix.target }}
        build-args: |
          PARENT_IMAGE=${{ needs.build-base.outputs.base_image }}
        cache-from: type=registry,ref=${{ env.REPO }}/base:ohpc
        push: true
