name: Package slinky-on-openshift chart

env:
  CHART_PATH: helm/slinky-on-openshift
  OCI_REGISTRY: oci://quay.io/slinky-on-openshift

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  helm-package-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.14.0'

    - name: Login to Quay.io
      run: |
        echo ${{ secrets.QUAY_PASSWORD }} | helm registry login quay.io --username ${{ secrets.QUAY_USERNAME }} --password-stdin

    - name: Update Helm dependencies
      run: |
        cd ${{ env.CHART_PATH }}
        helm dependency update

    - name: Package Helm chart
      run: |
        helm package ${{ env.CHART_PATH }}

    - name: Get chart version
      id: chart_version
      run: |
        CHART_VERSION=$(helm show chart ${{ env.CHART_PATH }} | grep '^version:' | awk '{print $2}')
        echo "version=${CHART_VERSION}" >> $GITHUB_OUTPUT
        echo "Chart version: ${CHART_VERSION}"

    - name: Push Helm chart to OCI registry
      run: |
        CHART_FILE="slinky-on-openshift-${{ steps.chart_version.outputs.version }}.tgz"
        helm push ${CHART_FILE} ${{ env.OCI_REGISTRY }}

    - name: Logout from registry
      if: always()
      run: |
        helm registry logout quay.io
